[package]
name = "ritec-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ritec-arena = { version = "0.1.0", path = "../ritec-arena" }
ritec-span = { version = "0.1.0", path = "../ritec-span" }
